# Generated by Django 2.2.6 on 2019-10-31 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portno', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AvailablePort',
                'verbose_name_plural': 'AvailablePort',
            },
        ),
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Key')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserKey',
                'verbose_name_plural': 'UsreKey',
            },
        ),
        migrations.CreateModel(
            name='AssignPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(db_index=True, max_length=20, verbose_name='User_IP')),
                ('user_port', models.IntegerField()),
                ('is_enable', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('assigned_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_available', to='api.AvailablePort')),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keys', to='api.UserKey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AssignPort',
                'verbose_name_plural': 'AssignPort',
            },
        ),
    ]
